# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f941a9b03dd4c645dcce7121361a57877784546745af42cb169014c2455058db7cbfcc42e4fcc5c54f4885c92327f7ef92a705f979d5538e4c4498be66b2f651

test:
  secret_key_base: e8db8f53a3078cea617bbd80766f16364ecb2bfd1e62ba1b8c9f8174a691aaa3b31c7525f7a04773d001b2a2b18cfde99ba2faf02af10420caf4befac69f6d60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
